### ISSUE TITLE
https://view.es-doc.org/ gets stuck?

### ISSUE THREAD

**Issue by jypeter** [ES-DOC/esdoc-web-view#1]
I'm not sure this is the right place to report this specific error

@momipsl I have just opened the following URL: https://view.es-doc.org/
and it gets stuck displaying
![es-doc-view-pb](https://user-images.githubusercontent.com/2785573/27084957-0acd83b8-504e-11e7-8033-5ede88649c2a.png)

Don't know if this is a feature or if the system is temporarily down. I get the same error in FF, Chrome and IE

**Comment by ghost** [comment]
[https://search.es-doc.org](https://search.es-doc.org) is the correct link, i.e. document search.

The search page correctly constructs links to the viewer page, e.g.: 

https://view.es-doc.org/?renderMethod=id&project=cmip6-draft&id=c397ecf5-3cd4-4eba-81cb-0173b711e996&version=1&client=esdoc-search

I will update the viewer page so as to redirect automatically to the search page if no URL parameters are supplied.
